# Generated by Django 4.2.18 on 2025-02-21 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservation_people_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
