# Generated by Django 4.2.18 on 2025-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_publishing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='currency',
            field=models.CharField(choices=[('EUR', '€'), ('USD', '$'), ('GBP', '£')], default='EUR', max_length=3),
        ),
    ]
