# Generated by Django 4.2.18 on 2025-02-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Dish',
        ),
    ]
