# Generated by Django 4.2.18 on 2025-02-11 11:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Recommended aspect ratio: 4:3 or 3:2 (e.g., 800×600 px, 1200×900 px, 900×600 px).', max_length=255, null=True, verbose_name='image'),
        ),
    ]
